#!/usr/bin/env python3
"""Build Top-5 daily paper digest from merged results.

Generates Markdown digest with title, abstract snippet, links, and tags.

Color scheme: #4A90D9 (primary), #E74C3C (alert).
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build Top-5 daily paper digest.")
    parser.add_argument("--input", "-i", required=True, help="Merged results JSON")
    parser.add_argument("--output", "-o", default=None, help="Output Markdown file")
    parser.add_argument("--top", "-n", type=int, default=5, help="Number of top papers")
    parser.add_argument("--template", default=None, help="Custom template file")
    parser.add_argument("--language", default="zh", choices=["zh", "en"])
    parser.add_argument("--verbose", "-v", action="store_true")
    return parser.parse_args()


def extract_tags(paper: dict) -> list[str]:
    """Extract relevant tags from paper metadata.

    Args:
        paper: Paper dict.

    Returns:
        List of tag strings.
    """
    tags: list[str] = []
    title_lower = (paper.get("title", "") + " " + paper.get("abstract", "")).lower()
    source = paper.get("source", "")

    tag_keywords = {
        "EEG": "eeg",
        "eye-tracking": "eye-tracking",
        "fNIRS": "fnirs",
        "facial": "facial-expression",
        "emotion": "emotion",
        "multimodal": "multimodal",
        "deep learning": "deep-learning",
        "BCI": "bci",
        "physiological": "physiological",
        "EEG+eye": "eeg-eye",
        "fusion": "fusion",
        "arousal": "arousal",
        "valence": "valence",
    }

    for label, tag in tag_keywords.items():
        if label.lower() in title_lower:
            tags.append(f"`{tag}`")

    if "arxiv" in source:
        tags.insert(0, "`arXiv`")
    elif "pubmed" in source:
        tags.insert(0, "`PubMed`")

    return tags[:6]  # Max 6 tags


def abstract_snippet(abstract: str, max_chars: int = 300) -> str:
    """Create a truncated abstract snippet.

    Args:
        abstract: Full abstract text.
        max_chars: Maximum characters.

    Returns:
        Truncated snippet with ellipsis.
    """
    if not abstract:
        return "*No abstract available*"
    if len(abstract) <= max_chars:
        return abstract
    return abstract[:max_chars].rsplit(" ", 1)[0] + "..."


def build_digest(
    papers: list[dict[str, Any]],
    top_n: int = 5,
    language: str = "zh",
) -> str:
    """Build Top-N paper digest Markdown.

    Args:
        papers: Merged paper list (already sorted).
        top_n: Number of top papers.
        language: Output language.

    Returns:
        Markdown string.
    """
    today = datetime.now().strftime("%Y-%m-%d")
    top_papers = papers[:top_n]

    if language == "zh":
        lines = [
            f"# 📚 每日文献速递 — {today}",
            "",
            f"**今日精选 {len(top_papers)} 篇多模态行为分析相关论文**",
            "",
            "---",
            "",
        ]
    else:
        lines = [
            f"# 📚 Daily Paper Digest — {today}",
            "",
            f"**Today's top {len(top_papers)} papers in multimodal behavioral analysis**",
            "",
            "---",
            "",
        ]

    for i, paper in enumerate(top_papers, 1):
        title = paper.get("title", "Untitled")
        authors = paper.get("authors", "Unknown")
        journal = paper.get("journal", "")
        pub_date = paper.get("pub_date", "")
        url = paper.get("url", "")
        doi = paper.get("doi", "")
        tags = extract_tags(paper)
        snippet = abstract_snippet(paper.get("abstract", ""))
        citations = paper.get("citation_count", "")

        lines.extend([
            f"## {i}. {title}",
            "",
            f"**Authors:** {authors}",
        ])

        if journal:
            lines.append(f"**Journal:** {journal}")
        if pub_date:
            lines.append(f"**Date:** {pub_date}")
        if citations:
            lines.append(f"**Citations:** {citations}")

        lines.append(f"**Tags:** {' '.join(tags)}")
        lines.append("")

        if url:
            lines.append(f"🔗 [{url}]({url})")
        if doi:
            lines.append(f"DOI: `{doi}`")

        lines.extend(["", f"> {snippet}", ""])

    # Stats footer
    total = len(papers)
    if language == "zh":
        lines.extend([
            "---",
            f"*本次检索共发现 {total} 篇论文，精选前 {len(top_papers)} 篇。*",
            f"*Generated by PsyPhiClaw Daily Paper · {today}*",
        ])
    else:
        lines.extend([
            "---",
            f"*{total} papers found, top {len(top_papers)} selected.*",
            f"*Generated by PsyPhiClaw Daily Paper · {today}*",
        ])

    return "\n".join(lines)


def main() -> int:
    args = parse_args()

    if not Path(args.input).exists():
        print("[#E74C3C] ERROR: File not found: {args.input}", file=sys.stderr)
        return 1

    with open(args.input) as f:
        papers = json.load(f)

    digest = build_digest(papers, args.top, args.language)

    out = args.output or f"digest_{datetime.now().strftime('%Y%m%d')}.md"
    with open(out, "w") as f:
        f.write(digest)

    print(f"[#4A90D9] ✓ Digest saved: {out} ({len(papers)} papers, top {args.top})")

    if args.verbose:
        print(digest[:500])

    return 0


if __name__ == "__main__":
    sys.exit(main())
